# GMediaRender configuration — system default (packaged)
# Users can override via ~/.config/gmediarender.conf

GMRENDER_FRIENDLY_NAME="Bureau"
GMRENDER_UUID="90aba109-6333-4669-85d1-d9316244f7f9"
GMRENDER_AUDIO_SINK="pulsesink"
GMRENDER_AUDIO_DEVICE="autoaudiosink"
GMRENDER_INITIAL_VOLUME_DB="0.0"